services:
  postgres:
    image: postgres:16
    container_name: coloriAI-postgres
    env_file:
      - .env.local
    ports:
      - 6432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: